### ISSUE TITLE
Lego Star Wars - Skywalker Saga able to port saves between switch/PC

### ISSUE THREAD

**Issue by tehblastar** [NS-cross-save-games/ns-cross-save-games.github.io#2]
Hey all,

Found out you are able to transfer save data both ways from Skywalker Saga between switch and PC. When exporting saves with JKSV, the output is a folder called SLOTX (X= save slot number) and profile data. Simply dragging and dropping that folder onto your save location folder on your PC and replacing the X with your preferred save slot (1-4) allows the PC to read the save. You will also instantly get all your steam achievements when launch the game.

The reverse is also possible and you can import saves from PC by importing the corresponding SLOT folder in JKSV. 

Super simple!

**Comment by GrayXu** [comment]
thanks!
